"""One-off patch: upgrade Section 6 from conjecture to theorem with proof (idempotent)."""
import pathlib
p = pathlib.Path(__file__).with_name("build_report.py")
s = p.read_text(encoding="utf-8")
if "Theorem 6.1" in s:
    print("already patched"); raise SystemExit

def rep(old, new):
    global s
    assert old in s, f"anchor not found: {old[:80]!r}"
    s = s.replace(old, new, 1)

# ---- header chip
rep(r'''<span class="chip">section 6: new result (conditional)</span>''', r'''<span class="chip">section 6: new theorem</span>''')

# ---- abstract
rep(r'''The closed forms are conjectural (a proof strategy is given); the finite-length theorem is rigorous for every \(n\) at which the coefficients are computed.</p>''',
    r'''The closed forms are proved: by Schur–Weyl duality each coefficient is a branching ratio times a squared SU(2) 6j-symbol with a spin-\(\tfrac12\) entry, and the eight resulting identities are verified by computer algebra. The improvement over the paper's Theorem 1.1 is therefore a theorem, resting only on the paper's general projection bound, Schur–Weyl duality, and Edmonds' table of 6j-symbols.</p>''')

# ---- tile
rep(r'''with MRRW2 at 0.25023; conditional on closed forms verified exactly on ~3,300 cases</div></div>''',
    r'''with MRRW2 at 0.25023; the coefficient formulas behind it are proved via Schur–Weyl duality and 6j-symbols</div></div>''')

# ---- section 6 intro sentence about the paper's theorem applying
rep(r'''So Theorem 4.2 applies verbatim once the directed squared coordinate coefficients \(p(\lambda\to\lambda')\) are known.</p>''',
    r'''So Theorem 4.2 applies verbatim once the directed squared coordinate coefficients \(p(\lambda\to\lambda')\) are known. Section 6.2 determines them exactly.</p>''')

# ---- 6.2: replace the conjecture paragraph with theorem + proof
rep(r'''<h3>6.2 Closed forms</h3>''', r'''<h3>6.2 Closed forms: Theorem 6.1</h3>''')
rep(r'''<p>These were found by exact interpolation in \(k\) at each vertex, followed by fitting the roots as linear forms and the prefactors by hand. They agree with every computed coefficient to \(3\times10^{-7}\) (floating-point noise in the projection), and the two identities that Theorem 4.2 requires hold <em>exactly in rational arithmetic</em>: the coefficients out of every admissible vertex sum to one (136,854 vertex–degree pairs, \(n\le40\)) and the dimension-weighted reciprocity \(D_\lambda p(\lambda\to\lambda')=D_{\lambda'}p(\lambda'\to\lambda)\) holds on every edge (523,432 edges, \(n\le36\)), with \(D_\lambda=\binom n{|\beta|}f^\alpha f^\beta\). We regard the closed forms as a conjecture with a clear proof route: the coefficient is the eigenvalue on \(S^\mu\) of a distance-one operator in the Hecke algebra of \((S_n,S_j\times S_{n-j})\) and is therefore a polynomial of degree at most two in \(k\); its roots are forced by the Littlewood–Richardson vanishing of the target; the prefactors are then fixed by the two identities.</p>''',
r'''<p><strong>Theorem 6.1.</strong> <em>For every admissible vertex and every admissible \(k\), the directed squared coordinate coefficients of the binary two-row graph are given by the eight formulas above; a move whose target does not contain \(E_\mu\) has coefficient zero. Moreover the coefficients out of every vertex sum to one, and \(D_\lambda p(\lambda\to\lambda')=D_{\lambda'}p(\lambda'\to\lambda)\) with \(D_\lambda=\binom n{|\beta|}f^\alpha f^\beta\).</em></p>
<p>The formulas were first found by exact interpolation in \(k\) at each computed vertex and then proved as follows. Write \(J=\tfrac n2-k\), \(j_\alpha=\tfrac{a_1-a_2}2\), \(j_\beta=\tfrac{b_1-b_2}2\); for a move that takes a box out of row \(r\) of \(\alpha\) into row \(r'\) of \(\beta\), put \(j_{\alpha'}=j_\alpha\mp\tfrac12\) (\(r=1,2\)) and \(j_\nu=j_\beta\pm\tfrac12\) (\(r'=1,2\)). The proof has three steps.</p>
<p><em>Step 1: fibres.</em> The sign group \(\mathbb Z_2^n\) acts on \(W\otimes V_\lambda\); on the block where the moving coordinate \(q\) is not in the sign set \(S\), the \(\chi_{S'}\)-eigenspace is \(G(S')=\bigoplus_{q\in S'}e_q\otimes\chi_{S'\setminus q}\otimes S^\beta(S'\setminus q)\otimes S^\alpha(S'^c\cup q)\), an \(S_{S'}\times S_{S'^c}\)-module isomorphic to \(\mathrm{Ind}_{S_j\times S_1}^{S_{j+1}}(S^\beta\boxtimes1)\boxtimes\mathrm{Res}^{S_{n-j}}_{S_{n-j-1}}S^\alpha=\bigoplus S^{\beta+\square}\boxtimes S^{\alpha-\square}\), multiplicity-free by Pieri's rule. The fibre of the constituent \(V_{\lambda'}\) over \(S'\) is the summand \(S^{\beta+\square_{r'}}\boxtimes S^{\alpha-\square_r}\), and \(\Pi_{\lambda'}\) is the sum of these isotypic projections. Hence \(p=\sum_{S'}\|\Pi_{r',r}u_{S'}\|^2/\|v\|^2\) with \(u_{S'}=n^{-1/2}(v_{S'\setminus q})_{q\in S'}\), where \(v=\varphi_\lambda Y\).</p>
<p><em>Step 2: the mass leaving a row.</em> The \(\alpha\)-projection acts slot by slot, and \(\sum_{q\in A}\Pi^{(q)}_{\alpha-\square_r}\) on \(S^\alpha(A)\) commutes with \(\mathrm{Sym}(A)\), hence is the scalar \(|A|\,f^{\alpha-\square_r}/f^\alpha\). Summing over \(S\) and \(q\notin S\) gives, for <em>every</em> \(v\in V_\lambda\), \(\sum_{r'}p(\alpha_r\to\beta_{r'})=\frac{|\alpha|}n\,\frac{f^{\alpha-\square_r}}{f^\alpha}\), independent of \(k\). (This is the row sum of the formulas: \(\frac{(a_1+1)(a_1-a_2)}{n(a_1-a_2+1)}\) and \(\frac{a_2(a_1-a_2+2)}{n(a_1-a_2+1)}\).)</p>
<p><em>Step 3: the split between the two \(\beta\)-rows.</em> By Frobenius reciprocity, which scales Hilbert–Schmidt norms by the index, \(p(\alpha_r\to\beta_{r'})=\frac{|\alpha|}n\frac{f^{\alpha-\square_r}}{f^\alpha}\,\rho_{r'}\), where \(\rho_{r'}\) is the squared cosine, in the two-dimensional space \(\mathrm{Hom}_{K_1}(\mathrm{Res}\,S^\mu,\,S^\beta\boxtimes1\boxtimes S^{\alpha'})\) with \(K_1=S_j\times S_1\times S_{n-j-1}\), of the angle between the line of maps factoring through \(S^\beta\boxtimes S^\alpha\) (the subgroup \(S_j\times S_{n-j}\)) and the line of maps factoring through \(S^{\beta+\square_{r'}}\boxtimes S^{\alpha'}\) (the subgroup \(S_{j+1}\times S_{n-j-1}\)); the two latter lines are orthogonal. Schur–Weyl duality on \((\mathbb C^2)^{\otimes n}\) identifies the two-row Specht module \(S^{(m-a,a)}\) with the SU(2) spin \(m/2-a\), restriction to a Young subgroup with the tensor product of the blocks, and the two-dimensional space above, isometrically up to a constant, with \(\mathrm{Hom}_{SU(2)}(V_J,\,V_{j_\beta}\otimes V_{1/2}\otimes V_{j_{\alpha'}})\); admissibility is the triangle inequality. The two lines are the two coupling schemes of three spins, so by the recoupling formula \(\rho_{r'}=(2j_\alpha+1)(2j_\nu+1)\begin{Bmatrix}j_\beta&\tfrac12&j_\nu\\ j_{\alpha'}&J&j_\alpha\end{Bmatrix}^2\). A 6j-symbol with a spin-\(\tfrac12\) entry has a closed form (Edmonds, Table 5), which we validated against exact values on all 1,326 admissible symbols with entries at most 5; substituting it, the product of branching ratio and squared recoupling coefficient simplifies, as an identity of rational functions of integer \(a_1,a_2,b_1,b_2,k\), to the eight displayed formulas (computer algebra, <code>experiments/hyperoct_proof_check.py</code>). Moves from \(\beta\) to \(\alpha\) follow by exchanging the roles of the two blocks. Finally the sum rule and the dimension-weighted reciprocity are identities of rational functions once the formulas are known, and both are verified symbolically in the same script. \(\square\)</p>
<p>Two remarks. The roots of each quadratic are the triangle-inequality boundaries of the recoupling, which is why they coincide with the Littlewood–Richardson admissibility boundaries of the target. And the formulas agree with all 3,340 coefficients computed independently by projection (Section 6.1) to \(3\times10^{-7}\), which is the floating-point noise of that computation; the exact identities above are the proof, the numerics were the discovery.</p>''')

# ---- 6.3: exponent statement as a theorem
rep(r'''<p>Two checks anchor this. At \(\tilde a=\tilde b=0\) the optimization reproduces \(\kappa_H\) to seven digits.''',
r'''<p><strong>Theorem 6.2.</strong> <em>For every \(0<\delta<\tfrac12\), \(R_2(\delta)\le\kappa_{2row}(\delta)\).</em> Proof. Fix an interior admissible point \((u,\tilde a,\tilde b,b)\) with \(\Lambda_\infty>1-2\delta\) and let \(\Omega_n\) be the box of side \(m_n\to\infty\), \(m_n=o(n)\), below the vertex \((un,\tilde an,\tilde bn)\) at \(k=\lfloor bn\rfloor\). By Theorem 6.1 the symmetric edge weights of the four directions converge uniformly on \(\Omega_n\) to \(\sqrt{A_1B_1}X/N_\infty\) and its three companions, so the product-sine Rayleigh quotient of the paper's Lemma 7.2 gives \(\lambda_{\max}(J_{\Omega_n})\ge\Lambda_\infty-o(1)\), while the row-sum bound gives the matching upper limit. Theorem 4.2 of the paper applies with \(G=B_n\), \(H=S_n\), \(E=E_\mu\) (multiplicity one, real endomorphisms, reciprocity by Theorem 6.1), so \(A_2(n,\lceil\delta n\rceil)\le\frac{1-s}{d_\mu(\lambda_{\max}-s)}\sum_{\Omega_n}D_\lambda\). The box has \(n^{o(1)}\) vertices and its largest dimension has exponent \(H_2(u)+(1-u)H_2(\tfrac{\tilde a}{1-u})+uH_2(\tfrac{\tilde b}u)+o(1)\) by Stirling, and \(d_\mu=2^{(H_2(b)+o(1))n}\). Taking logarithms, then the infimum over admissible points, and finally closing the strict inequality as in the paper's proof of Theorem 1.2, proves the claim. \(\square\)</p>
<p>Two checks anchor the optimization. At \(\tilde a=\tilde b=0\) it reproduces \(\kappa_H\) to seven digits.''')

# ---- 6.5 status
rep(r'''<h3>6.5 What is proven and what is conjectured</h3>
<ul>
<li><strong>Rigorous:</strong> for each finite \(n\) and each box \(\Omega\), the bound \(A_2(n,d)\le\frac{1-s}{d_\mu(\Lambda_\Omega-s)}\sum_{\lambda\in\Omega}D_\lambda\) follows from the paper's Theorem 4.2 with \(G=B_n\) once the coefficients are computed; we computed them exactly for \(n\le13\).</li>
<li><strong>Conjectural, heavily verified:</strong> the closed forms of Section 6.2 (every computed case, both identities exact on hundreds of thousands of cases, the correct classical specializations). The asymptotic exponent \(\kappa_{2row}\), the strict improvement over \(\kappa_H\), and the improvement over the paper's Theorem 1.1 for \(\delta\ge0.235\) are conditional on them.</li>
<li><strong>Independent evidence for the asymptotics:</strong> the exact recovery of \(M_2(\delta)\) at the middle level, a classical theorem obtained here from a different construction.</li>
</ul>
<div class="callout ok"><div class="t">Eureka, with its condition stated</div>Conditional on closed forms that hold in every one of roughly 3,300 exactly computed cases and satisfy the theorem's identities exactly, the binary two-row representation graph improves the best known upper bound on the rate of binary codes, \(R_2(\delta)\), for every \(\delta\in[0.235,0.5)\), beyond the bound proved in the paper. The mechanism is the paper's own (Proposition 7.3): a square-root spectral gain from opening a second row against a \(x\log(1/x)\) entropy cost. What remains is a proof of the eight formulas.</div>''',
r'''<h3>6.5 What is proven</h3>
<ul>
<li><strong>Theorem 6.1</strong> (the coefficients) rests on three standard inputs: Frobenius reciprocity, Schur–Weyl duality for two-row shapes, and the recoupling formula with Edmonds' closed form for spin-\(\tfrac12\) 6j-symbols (the last validated against exact values on all 1,326 admissible symbols with entries at most 5). The final simplification is a computer-algebra identity of rational functions.</li>
<li><strong>Finite lengths:</strong> for each \(n\) and box \(\Omega\), \(A_2(n,d)\le\frac{1-s}{d_\mu(\Lambda_\Omega-s)}\sum_{\lambda\in\Omega}D_\lambda\) is the paper's Theorem 4.2 with \(G=B_n\), whose hypotheses Theorem 6.1 supplies.</li>
<li><strong>Theorem 6.2</strong> (the exponent) follows by the paper's own box argument. The numerical statements, \(\kappa_{2row}<\kappa_H\) everywhere and \(\kappa_{2row}<\kappa_{\rm bin}\) for \(\delta\ge\delta_1\), are then evaluations of an explicit four-parameter infimum; the margins (\(10^{-3}\) to \(5\times10^{-6}\)) are far above the optimizer's precision, and the exact recovery of \(M_2(\delta)\) at the middle level is an independent check of the whole reduction.</li>
</ul>
<div class="callout ok"><div class="t">Eureka</div>The binary two-row representation graph improves the best known upper bound on the rate of binary codes, \(R_2(\delta)\), for every \(\delta\in[0.235,0.5)\), beyond the bound proved in OpenAI's paper. The coefficients are proved (Theorem 6.1), the exponent follows by the paper's own machinery (Theorem 6.2), and the mechanism is the paper's Proposition 7.3 transplanted to the cube: a square-root spectral gain from opening a second row against an \(x\log(1/x)\) entropy cost. The standard facts used are Schur–Weyl duality, Frobenius reciprocity, and Edmonds' table of 6j-symbols; every algebraic step is checked by computer algebra in the results folder.</div>''')

# ---- establishes bullets
rep(r'''<li><strong>Section 6 is different in kind.</strong> It is our construction, not the paper's, and it rests on conjectured closed forms. Everything downstream of them is stated as conditional, and the finite-length theorem is the only unconditional part.</li>
<li><strong>Not covered:</strong> the Lean formalization itself, everything outside Chapter 2 of the paper, and a proof of the closed forms of Section 6.2.</li>''',
r'''<li><strong>Section 6 is different in kind.</strong> It is our construction, not the paper's: a new theorem (6.1 and 6.2) proved with standard representation theory on top of the paper's general projection bound, with every algebraic identity machine-checked. A formal (Lean) proof has not been attempted.</li>
<li><strong>Not covered:</strong> the Lean formalization itself and everything outside Chapter 2 of the paper.</li>''')

# ---- method list
rep(r'''experiments/hyperoct_collect.py / hyperoct_roots.py / hyperoct_formulas.py / hyperoct_verify_big.py / hyperoct_exponent.py / hyperoct_finite.py / make_figure5.py</code></pre>''',
    r'''experiments/hyperoct_collect.py / hyperoct_roots.py / hyperoct_formulas.py / hyperoct_verify_big.py / hyperoct_exponent.py / hyperoct_finite.py / make_figure5.py
experiments/hyperoct_proof_check.py  the proof's algebra: Edmonds 6j table vs exact values; the eight identities; sum rule; reciprocity</code></pre>''')

p.write_text(s, encoding="utf-8")
print("patched build_report.py (proof)")
